FROM tacc/tacc-ubuntu18-impi19.0.7-common:latest

RUN apt-get update && apt-get upgrade -y && apt-get install -y python3-pip
RUN . /opt/intel/compilers_and_libraries/linux/mpi/intel64/bin/mpivars.sh; pip3 install mpi4py

COPY pi-mpi.py /code/pi-mpi.py
RUN chmod +x /code/pi-mpi.py

ENV PATH "/code:$PATH"
